#!/usr/bin/env node
// Generated by scripts/build-adapters.mjs — do not edit.
// Translates Cursor hook JSON <-> the Claude-Code-shaped payloads Archflow's hook scripts expect.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const event = process.argv[2];
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
let input = {};
try { input = JSON.parse(readFileSync(0, "utf8") || "{}"); } catch {}
const cwd = input.cwd || process.cwd();
const isArchflow = existsSync(join(cwd, ".archflow"));
const env = { ...process.env, CLAUDE_PLUGIN_ROOT: root, CLAUDE_PROJECT_DIR: cwd, ARCHFLOW_HOST: "cursor" };
const run = (script, payload) =>
  spawnSync("node", [join(here, script)], { cwd, env, input: JSON.stringify(payload), encoding: "utf8", timeout: 6000 });
const out = (o) => { process.stdout.write(JSON.stringify(o)); process.exit(0); };

if (!isArchflow) out({});

if (event === "sessionStart") {
  const parts = [];
  try { parts.push(readFileSync(join(cwd, ".archflow", "instructions.md"), "utf8")); } catch {}
  const r = run("check-upgrade.mjs", { hook_event_name: "SessionStart", cwd });
  if (r.stdout?.trim()) parts.push(r.stdout.trim());
  out(parts.length ? { additional_context: parts.join("\n\n") } : {});
}
if (event === "beforeShellExecution") {
  const r = run("guard-git.mjs", { hook_event_name: "PreToolUse", tool_name: "Bash", tool_input: { command: input.command }, cwd });
  if (r.status === 2) {
    const msg = (r.stderr || "Blocked by Archflow git guard").trim();
    out({ permission: "deny", user_message: msg.split("\n")[0], agent_message: msg });
  }
  out({ permission: "allow" });
}
if (event === "stop") {
  const r = run("check-state.mjs", { hook_event_name: "Stop", cwd });
  if (r.stdout?.trim()) console.error(r.stdout.trim()); // advisory; Cursor's stop output is only for follow-ups
  out({});
}
out({});
