#!/usr/bin/env node
// Generated by scripts/build-adapters.mjs — do not edit.
// Translates Cursor hook JSON <-> the Claude-Code-shaped payloads Archflow's hook scripts expect.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const event = process.argv[2];
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
let input = {};
try { input = JSON.parse(readFileSync(0, "utf8") || "{}"); } catch {}
// Cursor sends no cwd. Use the first workspace root that is an Archflow project, else the first root,
// so a multi-root workspace whose Archflow project is not listed first still gets its hooks.
const roots = Array.isArray(input.workspace_roots) ? input.workspace_roots.filter((r) => typeof r === "string" && r) : [];
const cwd = input.cwd || roots.find((r) => existsSync(join(r, ".archflow"))) || roots[0] || process.cwd();
const isArchflow = existsSync(join(cwd, ".archflow"));
const env = { ...process.env, CLAUDE_PLUGIN_ROOT: root, CLAUDE_PROJECT_DIR: cwd, ARCHFLOW_HOST: "cursor" };
const run = (script, payload, args = []) =>
  spawnSync("node", [join(here, script), ...args], { cwd, env, input: JSON.stringify(payload), encoding: "utf8", timeout: 6000 });
const out = (o) => { process.stdout.write(JSON.stringify(o)); process.exit(0); };

// Telemetry runs in every workspace, like the Claude Code plugin; the rest only in Archflow projects.
if (event === "beforeSubmitPrompt") {
  // Observation only: always continue, whatever the telemetry script does.
  run("telemetry.mjs", { prompt: input.prompt, cwd }, ["--prompt"]);
  out({ continue: true });
}
if (event === "sessionStart") {
  const parts = [];
  const t = run("telemetry.mjs", { hook_event_name: "SessionStart", cwd });
  if (t.stdout?.trim()) parts.push(t.stdout.trim());
  if (isArchflow) {
    try { parts.push(readFileSync(join(cwd, ".archflow", "instructions.md"), "utf8")); } catch {}
    const r = run("check-upgrade.mjs", { hook_event_name: "SessionStart", cwd });
    if (r.stdout?.trim()) parts.push(r.stdout.trim());
  }
  out(parts.length ? { additional_context: parts.join("\n\n") } : {});
}
if (!isArchflow) out({});

if (event === "beforeShellExecution") {
  const r = run("guard-git.mjs", { hook_event_name: "PreToolUse", tool_name: "Bash", tool_input: { command: input.command }, cwd });
  if (r.status === 2) {
    const msg = (r.stderr || "Blocked by Archflow git guard").trim();
    out({ permission: "deny", user_message: msg.split("\n")[0], agent_message: msg });
  }
  out({ permission: "allow" });
}
if (event === "stop") {
  const r = run("check-state.mjs", { hook_event_name: "Stop", cwd });
  // check-state reports drift on stderr. Advisory: Cursor's stop stdout is only for follow-ups.
  const msg = (r.stderr || r.stdout || "").trim();
  if (msg) console.error(msg);
  out({});
}
out({});
