#!/usr/bin/env bash
# Snapshot GitHub traffic stats into metrics/*.csv.
#
# GitHub only retains 14 days of traffic data, so this is run daily to build a
# permanent series. Rows are keyed by date and overwritten on each run: counts
# for recent days keep incrementing, so the newest fetch always wins.
#
# Requires a token with push access (traffic API is not readable by the default
# Actions GITHUB_TOKEN). Set GH_TOKEN.
set -euo pipefail

REPO="${REPO:-AZidan/archflow}"
OUT_DIR="${OUT_DIR:-metrics}"
DAILY="$OUT_DIR/traffic.csv"
REFERRERS="$OUT_DIR/referrers.csv"
TODAY="$(date -u +%F)"

mkdir -p "$OUT_DIR"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh api "repos/$REPO/traffic/clones" > "$tmp/clones.json"
gh api "repos/$REPO/traffic/views"  > "$tmp/views.json"
gh api "repos/$REPO/traffic/popular/referrers" > "$tmp/referrers.json"

# --- daily clones + views, joined by date ---
jq -rn \
  --slurpfile c "$tmp/clones.json" \
  --slurpfile v "$tmp/views.json" '
  ($c[0].clones // []) as $cl
  | ($v[0].views // []) as $vw
  | ([$cl[].timestamp[0:10]] + [$vw[].timestamp[0:10]] | unique)[] as $d
  | ([$cl[] | select(.timestamp[0:10] == $d)][0]) as $cd
  | ([$vw[] | select(.timestamp[0:10] == $d)][0]) as $vd
  | [$d, ($cd.count // 0), ($cd.uniques // 0), ($vd.count // 0), ($vd.uniques // 0)]
  | map(tostring) | join(",")
' > "$tmp/new-daily.csv"

# Later occurrence wins, so fresh rows overwrite stored ones for the same date.
{ [ -f "$DAILY" ] && tail -n +2 "$DAILY"; cat "$tmp/new-daily.csv"; } \
  | awk -F, 'NF && $1 != "date" { rows[$1] = $0 } END { for (d in rows) print rows[d] }' \
  | sort > "$tmp/merged-daily.csv"

{ echo "date,clones,clone_uniques,views,view_uniques"; cat "$tmp/merged-daily.csv"; } > "$DAILY"

# --- referrers: a rolling 14-day aggregate, so store one snapshot per run date ---
jq -r --arg d "$TODAY" '.[] | [$d, .referrer, .count, .uniques] | map(tostring) | join(",")' \
  "$tmp/referrers.json" > "$tmp/new-referrers.csv"

{ [ -f "$REFERRERS" ] && tail -n +2 "$REFERRERS" | grep -v "^$TODAY," || true; \
  cat "$tmp/new-referrers.csv"; } \
  | awk 'NF' | sort > "$tmp/merged-referrers.csv"

{ echo "snapshot_date,referrer,count,uniques"; cat "$tmp/merged-referrers.csv"; } > "$REFERRERS"

# --- rendered summary: GitHub renders Mermaid in Markdown, so this is the view ---
CHART_DAYS=30
tail -n +2 "$DAILY" | tail -n "$CHART_DAYS" > "$tmp/chart-rows.csv"

labels=$(awk -F, '{printf "\"%s\", ", substr($1,6)}' "$tmp/chart-rows.csv" | sed 's/, $//')
uniques=$(awk -F, '{printf "%s, ", $3}' "$tmp/chart-rows.csv" | sed 's/, $//')
ymax=$(awk -F, 'BEGIN{m=0} {if ($3+0 > m) m=$3+0} END{print (m<5 ? 5 : int(m*1.2)+1)}' "$tmp/chart-rows.csv")

# Unique cloners are per-day uniques; summing across days double-counts anyone
# who cloned on more than one day. Totals are an upper bound, not a headcount.
read -r c7 u7   < <(tail -n 7  "$tmp/chart-rows.csv" | awk -F, '{c+=$2; u+=$3} END{print c+0, u+0}')
read -r c30 u30 < <(awk -F, '{c+=$2; u+=$3} END{print c+0, u+0}' "$tmp/chart-rows.csv")
first_day=$(head -1 "$tmp/chart-rows.csv" | cut -d, -f1)
last_day=$(tail -1 "$tmp/chart-rows.csv" | cut -d, -f1)

cat > "$OUT_DIR/README.md" <<MD
# Traffic metrics

Auto-generated by [\`.github/workflows/traffic-metrics.yml\`](../.github/workflows/traffic-metrics.yml).
Do not edit by hand — changes are overwritten on the next run.

GitHub retains only 14 days of traffic data, so these snapshots are the permanent
record. Clone counts are the closest available proxy for plugin installs: a
\`/plugin marketplace add\` is a \`git clone\`, and Anthropic publishes no install stats.

Last updated: $TODAY · window shown: $first_day → $last_day

## Unique cloners per day

\`\`\`mermaid
xychart-beta
    title "Unique cloners per day"
    x-axis [$labels]
    y-axis "Unique cloners" 0 --> $ymax
    line [$uniques]
\`\`\`

## Totals

| Window | Clones | Unique cloners |
|---|---:|---:|
| Last 7 days | $c7 | $u7 |
| Last 30 days | $c30 | $u30 |

Unique cloners is a *per-day* figure, so these column totals double-count anyone
who cloned on more than one day — read them as an upper bound, not a headcount.

A high clones-to-uniques ratio (~10:1) indicates automation; roughly 1–2:1 is
human traffic. Raw data: [\`traffic.csv\`](traffic.csv), [\`referrers.csv\`](referrers.csv).
MD

echo "Wrote $DAILY ($(($(wc -l < "$DAILY") - 1)) days), $REFERRERS, and $OUT_DIR/README.md"
