// Generated by scripts/build-adapters.mjs — do not edit.
// Bridges Archflow's Claude-Code-shaped hook scripts to OpenCode's plugin API.
import type { Plugin } from "@opencode-ai/plugin"
import { spawnSync } from "node:child_process"
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

const ROOT = ".opencode/archflow"

function runHook(cwd: string, script: string, payload: object): { code: number; stdout: string; stderr: string } {
  const r = spawnSync("node", [join(cwd, ROOT, "hooks", script)], {
    cwd,
    input: JSON.stringify(payload),
    encoding: "utf8",
    timeout: 6000,
    env: { ...process.env, CLAUDE_PLUGIN_ROOT: join(cwd, ROOT), CLAUDE_PROJECT_DIR: cwd },
  })
  return { code: r.status ?? 0, stdout: r.stdout ?? "", stderr: r.stderr ?? "" }
}

export const ArchflowPlugin: Plugin = async ({ directory }) => {
  const cwd = directory
  const isArchflow = () => existsSync(join(cwd, ".archflow"))

  return {
    // SessionStart equivalent: inject instructions.md + upgrade notice into the system prompt.
    "experimental.chat.system.transform": async (_input, output) => {
      if (!isArchflow()) return
      const parts: string[] = []
      try { parts.push(readFileSync(join(cwd, ".archflow", "instructions.md"), "utf8")) } catch {}
      const up = runHook(cwd, "check-upgrade.mjs", { hook_event_name: "SessionStart", cwd })
      if (up.stdout.trim()) parts.push(up.stdout)
      if (parts.length) output.system.push(parts.join("\n\n"))
    },
    // Keep instructions after compaction, mirroring the Claude Code `compact` matcher.
    "experimental.session.compacting": async (_input, output) => {
      if (!isArchflow()) return
      try { output.context.push(readFileSync(join(cwd, ".archflow", "instructions.md"), "utf8")) } catch {}
    },
    // PreToolUse[Bash] equivalent: git guard. Exit 2 from the script = block.
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "bash" || !isArchflow()) return
      const r = runHook(cwd, "guard-git.mjs", {
        hook_event_name: "PreToolUse",
        tool_name: "Bash",
        tool_input: { command: output.args?.command },
        cwd,
      })
      if (r.code === 2) throw new Error(r.stderr.trim() || "Blocked by Archflow git guard")
    },
    // Stop equivalent: schema drift warning when the session goes idle.
    // (session.idle is a bus event, not a named hook.)
    event: async ({ event }) => {
      if (event.type !== "session.idle" || !isArchflow()) return
      const r = runHook(cwd, "check-state.mjs", { hook_event_name: "Stop", cwd })
      if (r.stdout.trim()) console.warn(r.stdout.trim())
    },
  }
}

export default ArchflowPlugin
